spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://clozet.cbmmf1db7skg.ap-northeast-2.rds.amazonaws.com/clozet?characterEncoding=UTF-8&serverTimezone=UTC
    username: clozet
    password: clozetdb
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
      location: C:\
      file-size-threshold: 1MB

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true #To beautify or pretty print the SQL
        show_sql: true #show sql

security:
  jwt:
    token:
      security-key: secret-key
      expiration-length: 3600000

server:
  port: 8080

logging:
  level:
    org.hibernate:
      type.descriptor.sql: trace #show parameter binding
      SQL: DEBUG


